name: Laravel-CI

on:
  push:
    branches: [ main, feature ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-install-to-test:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.2.5
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

    - name: Install PHP Dependencies
      run: composer update
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Install JS Dependecies
      run: npm install
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
        php artisan migrate    
    
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit --testdox
  
  laravel-deploy:
    needs: laravel-install-to-deploy
    runs-on: ubuntu-latest
    
    steps: 
    - name: Log some info
      run: echo 'Start to deploy...'