name: Laravel-CI

on:
  push:
    branches: [ main, feature ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-install-to-test:

    runs-on: ubuntu-latest
    # Service container Mysql mysql
    services:
      # Label used to access the service container
      mysql:
        # Docker Hub image (also with version)
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD_LARAVEL_CI }}
          MYSQL_DATABASE:  laravel_ci
        ## map the "external" 33306 port with the "internal" 3306
        ports:
          - 33306:3306
        # Set health checks to wait until mysql database has started (it takes some seconds to start)
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:    
    - uses: actions/checkout@v2    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.2.5
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

    - name: Install PHP Dependencies
      run: composer update
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Install JS Dependecies
      run: npm install
    - name: Create Database & make migrations
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: laravel_ci
        DB_PORT: 33306
        DB_USER: root
        DB_PASSWORD: ${{ secrets.DB_PASSWORD_LARAVEL_CI }}
      run: php artisan migrate    
         
    - name: Run test by PHPUnit
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: laravel_ci
        DB_PORT: 33306
        DB_USER: root
        DB_PASSWORD: ${{ secrets.DB_PASSWORD_LARAVEL_CI }}
      run: vendor/bin/phpunit --testdox         

    - name: Execute Code Static Analysis (PHP Stan + Larastan)
      run: |
        composer require --dev nunomaduro/larastan
        vendor/bin/phpstan analyse app -c ./vendor/nunomaduro/larastan/extension.neon  --level=4 --no-progress 
  
  laravel-deploy:
    needs: laravel-install-to-test
    runs-on: ubuntu-latest

    steps: 
    - name: Log some info
      run: echo 'Start to deploy...'